server:
  port: 9001

spring:
  application:
    name: legacy
  datasource:
    url: jdbc:oracle:thin:@192.168.0.160:1521:xe
    username: gioconda
    password: q1w2e3
    hikari:
      maximum-pool-size: 1
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  zipkin:
    base-url: http://localhost:9411