server:
  port: 9001
  error:
    include-message: always

spring:
  application:
    name: legacy
  datasource:
    url: jdbc:oracle:thin:@gioconda_high?TNS_ADMIN=/Users/vdcoelho/Development/Wallet_gioconda/
    username: admin
    password: F*KAhWn*IJlCDpn83$9A
    driver:
      class: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  zipkin:
    base-url: http://localhost:9411